name: 'Create Release'
description: 'Creates a GitHub release for any pipeline stage (deployment, signoff, production)'
author: 'Optivem'
branding:
  icon: 'tag'
  color: 'blue'

inputs:
  base-version:
    description: 'Original version that triggered the workflow (e.g., v1.0.4-rc)'
    required: true
  release-version:
    description: 'Release version tag to create (e.g., v1.0.4-rc-qa-deployed)'
    required: true
  environment:
    description: 'Environment name (e.g., qa, staging, prod)'
    required: true
  status:
    description: 'Status (e.g., deployed, passed, failed)'
    required: true
  artifact-urls:
    description: 'JSON array of artifact URLs (Docker images, packages, etc.)'
    required: false
    default: '[]'
  is-prerelease:
    description: 'Whether this is a prerelease'
    required: false
    default: 'true'

outputs:
  release-url:
    description: 'URL of the created GitHub release'
    value: ${{ steps.create-release.outputs.release-url }}

runs:
  using: 'composite'
  steps:
    - name: Create Release
      id: create-release
      run: |
        $scriptPath = Join-Path ${{ github.action_path }} "Create-Release.ps1"
        & $scriptPath `
          -StatusVersion "${{ inputs.release-version }}" `
          -OriginalVersion "${{ inputs.base-version }}" `
          -Environment "${{ inputs.environment }}" `
          -Status "${{ inputs.status }}" `
          -ArtifactUrls '${{ inputs.artifact-urls }}' `
          -IsPrerelease $${{ inputs.is-prerelease }} `
          -GitHubToken "${{ env.GITHUB_TOKEN }}" `
          -Repository "${{ github.repository }}" `
          -ServerUrl "${{ github.server_url }}" `
          -RunId "${{ github.run_id }}" `
          -CommitSha "${{ github.sha }}" `
          -Actor "${{ github.actor }}"
      shell: pwsh
      env:
        GH_TOKEN: ${{ env.GITHUB_TOKEN }}